version: '3'
services:
  mysql:
    image: mysql:5.6
    volumes:
      - "./data/db:/var/lib/mysql"
    ports:
      - "3306:3306"
    env_file: .env
  # mailcatcher:
  #    image: schickling/mailcatcher
  #    # restart: always
  #    ports:
  #      - "1025:1025"
  #      - "1080:1080"
  #    env_file: .env
  # memcached:
  #   image: memcached:1.5
  #   # restart: always
  # elasticsearch:
  #   image: elasticsearch:5
  #   # restart: always
  #   env_file: .env
  #   # environment:
  #   #  ES_JAVA_OPTS: "-Xms750m -Xmx750m"
  #   ports:
  #     - "9200:9200"
  #   volumes:
  #     - "./config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
  #     - "./config/elasticsearch/plugins:/usr/share/elasticsearch/plugins"
  phpfpm:
    image: 10up/phpfpm
    depends_on:
      - mysql
      # - memcached
      # - elasticsearch
    volumes:
      - "./bin:/docker/bin"
      - "./data/dumps:/docker/dumps"
      - "./config/php-fpm/php.ini:/usr/local/etc/php/php.ini"
      - "./config/php-fpm/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
      - "./public_html:/var/www/html"
    env_file: .env
    extra_hosts:
      - "docker-local.dev:172.18.0.1"
  nginx:
    depends_on:
      - phpfpm
    ports:
      - "80:80"
      - "443:443"
    image: nginx:latest
    volumes:
      - "./public_html:/var/www/html"
      - "./config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./config/certs:/etc/nginx/certs"
